on:
  create:
    ref_type: branch
jobs:
  auto-assign:
    runs-on: ubuntu-latest
    steps:
      - name: Extract issue number from branch name
        id: extract
        run: |
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          ISSUE_NUM=$(echo "$BRANCH_NAME" | grep -oE '^[0-9]+')
          echo "Extracted issue number: $ISSUE_NUM"
          echo "::set-output name=issue_number::$ISSUE_NUM"

      - name: Assign issue to branch creator
        if: ${{ steps.extract.outputs.issue_number != '' }}
        run: |
          echo "Assigning issue #${{ steps.extract.outputs.issue_number }} to ${{ github.actor }}"
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/issues/${{ steps.extract.outputs.issue_number }}/assignees \
            -d "{\"assignees\": [\"${{ github.actor }}\"]}"
